export const weights = [
    {
        id:0,
        name:"PH",
        weight:"5",
        category:"有機"
    },
    {
        id:1,
        name:"FD",
        weight:"5",
        category:"有機"
    },
    {
        id:2,
        name:"PH(ISO)",
        weight:"6",
        category:"有機"
    },
    {
        id:3,
        name:"FD(ISO)",
        weight:"4",
        category:"有機"
    },
    {
        id:4,
        name:"AZO(A)",
        weight:"5",
        category:"有機"
    },
    {
        id:5,
        name:"AZO(B)",
        weight:"8",
        category:"有機"
    },
    {
        id:6,
        name:"AZO(C)",
        weight:"10",
        category:"有機"
    },
    {
        id:7,
        name:"一般材質",
        weight:"5",
        category:"材質"
    },
    {
        id:8,
        name:"塑印",
        weight:"7",
        category:"材質"
    },
    {
        id:9,
        name:"Button Cell",
        weight:"8",
        category:"材質"
    },
    {
        id:10,
        name:"其他電池",
        weight:"15",
        category:"材質"
    },
    {
        id:11,
        name:"烘乾",
        weight:"15",
        category:"材質"
    },
    {
        id:12,
        name:"貼樣",
        weight:"1",
        category:"材質"
    },
    {
        id:13,
        name:"0.01g",
        weight:"5",
        category:"Coating"
    },
    {
        id:14,
        name:"0.02g",
        weight:"6",
        category:"Coating"
    },
    {
        id:15,
        name:"0.03g",
        weight:"7",
        category:"Coating"
    },
    {
        id:16,
        name:"0.05g",
        weight:"8",
        category:"Coating"
    },
    {
        id:17,
        name:"0.06g",
        weight:"8",
        category:"Coating"
    },
    {
        id:18,
        name:"0.09g",
        weight:"9",
        category:"Coating"
    },
    {
        id:19,
        name:"0.1g",
        weight:"9",
        category:"Coating"
    },
    {
        id:20,
        name:"0.25g",
        weight:"15",
        category:"Coating"
    },
    {
        id:21,
        name:"0.5g",
        weight:"25",
        category:"Coating"
    },
    {
        id:22,
        name:">1g or 難刮",
        weight:"40",
        category:"Coating"
    },
    {
        id:23,
        name:"0.5hr",
        weight:"30",
        category:"電子組"
    },
    {
        id:24,
        name:"1hr",
        weight:"60",
        category:"電子組"
    },
    {
        id:25,
        name:"1.5hr",
        weight:"90",
        category:"電子組"
    },
    {
        id:26,
        name:"2hr",
        weight:"120",
        category:"電子組"
    },
    {
        id:27,
        name:"2.5hr",
        weight:"150",
        category:"電子組"
    },
    {
        id:28,
        name:"3hr",
        weight:"180",
        category:"電子組"
    },
    {
        id:29,
        name:"3.5hr",
        weight:"210",
        category:"電子組"
    },
    {
        id:30,
        name:"4hr",
        weight:"240",
        category:"電子組"
    },
    {
        id:31,
        name:"0.5hr",
        weight:"30",
        category:"支援"
    },
    {
        id:32,
        name:"1hr",
        weight:"60",
        category:"支援"
    },
    {
        id:33,
        name:"1.5hr",
        weight:"90",
        category:"支援"
    },
    {
        id:34,
        name:"2hr",
        weight:"120",
        category:"支援"
    },
    {
        id:35,
        name:"2.5hr",
        weight:"150",
        category:"支援"
    },
    {
        id:28,
        name:"3hr",
        weight:"180",
        category:"支援"
    },
    {
        id:36,
        name:"3.5hr",
        weight:"210",
        category:"支援"
    },
    {
        id:37,
        name:"4hr",
        weight:"240",
        category:"支援"
    }
]